system_prompt = read_file("system_prompt.txt")

example0.5 = "Carlos (M, 42) met his colleague Maria (29, F) at a workplace in Barcelona, Spain, (41.3851, 2.1734) on 12 November 2022. Carlos had been feeling unwell for two days. On 18 November, Carlos was admitted to Hospital Clinic Barcelona and tested positive for H1N1 influenza. He was released from the hospital on 25 November. Maria developed symptoms on 19 November, and their flu test came back positive two days later. They recovered at home without requiring hospitalization on the 26 November."

example1 = "Carlos (M, 42) met his colleagues Maria (29, F), Javier (35, M), and Marta (F, 32) at a workplace in Barcelona, Spain, (41.3851, 2.1734) on 12 November 2022. Carlos had been feeling unwell for two days. On 18 November, Carlos was admitted to Hospital Clinic Barcelona and tested positive for H1N1 influenza. He was released from the hospital on 25 November. Maria and Javier developed symptoms on 19 November, and their flu tests came back positive two days later. They both recovered at home without requiring hospitalization by 26 November and 1 December, respectively. Marta fell ill on 20 November and tested positive on 21 November. She was admitted to Hospital Clinic Barcelona on 23 November and was discharged after a week."

example2 = "John (M, 38) attended a family gathering in New York City, USA (40.7128, -74.0060) on 15 December 2022, where he interacted with his relatives, Emily (F, 45), Michael (M, 42), and Olivia (F, 40). John started experiencing symptoms on 20 December and tested positive for COVID-19 on 22 December. He self-isolated at home and recovered by 2 January 2023. Emily and Michael developed symptoms on 21 December, and their COVID-19 test results returned positive on 23 December. They both recovered at home without hospitalization by 3 January and 5 January, respectively. Olivia fell ill on 22 December and tested positive on 24 December. She was admitted to Mount Sinai Hospital on 26 December and was discharged after ten days."

example3 = "Ravi (M, 48) attended a religious ceremony in Colombo, Sri Lanka (6.9271, 79.8612) on 10 February 2023, where he came in contact with his friends Priya (F, 35), Anura (M, 40), Nisha (F, 33), Dilan (M, 45), and Kavitha (F, 37). Ravi started showing symptoms on 15 February and tested positive for Nipah virus on 17 February. He was admitted to the National Hospital of Sri Lanka on 20 February and recovered after two weeks. Priya and Anura developed symptoms on 16 February, and their Nipah virus test results returned positive on 18 February. They both were hospitalized at the National Hospital of Sri Lanka and unfortunately succumbed to the infection on 25 February and 27 February, respectively. Nisha fell ill on 17 February and tested positive on 19 February. She was admitted to Colombo General Hospital on 21 February and was released after nine days. Dilan and Kavitha began exhibiting symptoms on 18 February, and their Nipah virus test results came back positive on 20 February. They were both admitted to Colombo General Hospital on 22 February. Despite the medical team's efforts, Dilan passed away on 28 February, and Kavitha on 2 March. The remaining contacts were closely monitored and quarantined as a precautionary measure to prevent further spread of the virus."
